### ISSUE TITLE
Deprecated php Code

### ISSUE THREAD

**Issue by crownddy** [danflood94/phonegap#1]
Thanks for the code. 
I have once test the code which works fine but now after updating my system, 
The php keep throwing error it won't login or sign up. 
And it like the php code is deprecated, can you please  update it.

**Comment by danflood94** [comment]
Sorry, this project is over 5 years old and is not being maintained. The code did not ever represent best practice as the login is not secure, which was the purpose of a later project for a class I was teaching. You should consider it dead.
